// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE0kULZH6WBshxrsuv7F_1_x_x7vcOWY',
    appId: '1:872382998383:web:24ed2ba8040c6d9160ea9a',
    messagingSenderId: '872382998383',
    projectId: 'auth-practice-af792',
    authDomain: 'auth-practice-af792.firebaseapp.com',
    storageBucket: 'auth-practice-af792.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0DYju8QP5cegZRWafefepmjSl6FDNhc',
    appId: '1:872382998383:android:dcdfb5d2a0e4e1ff60ea9a',
    messagingSenderId: '872382998383',
    projectId: 'auth-practice-af792',
    storageBucket: 'auth-practice-af792.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_yTmprI40lpzCNGZR-q-8JHS_xNf52k',
    appId: '1:872382998383:ios:65438016447bdfc560ea9a',
    messagingSenderId: '872382998383',
    projectId: 'auth-practice-af792',
    storageBucket: 'auth-practice-af792.firebasestorage.app',
    iosBundleId: 'com.example.authenticationPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_yTmprI40lpzCNGZR-q-8JHS_xNf52k',
    appId: '1:872382998383:ios:65438016447bdfc560ea9a',
    messagingSenderId: '872382998383',
    projectId: 'auth-practice-af792',
    storageBucket: 'auth-practice-af792.firebasestorage.app',
    iosBundleId: 'com.example.authenticationPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCE0kULZH6WBshxrsuv7F_1_x_x7vcOWY',
    appId: '1:872382998383:web:36b84d062751d96860ea9a',
    messagingSenderId: '872382998383',
    projectId: 'auth-practice-af792',
    authDomain: 'auth-practice-af792.firebaseapp.com',
    storageBucket: 'auth-practice-af792.firebasestorage.app',
  );
}
