// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfHaQsU2wVPKRDvvOcadfE2rglY3jpwI',
    appId: '1:835117534469:web:7a9222eafb49e6030bbb6c',
    messagingSenderId: '835117534469',
    projectId: 'crud-tutorial-8cb44',
    authDomain: 'crud-tutorial-8cb44.firebaseapp.com',
    storageBucket: 'crud-tutorial-8cb44.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnUdXs3UY8UNXckCAO5AeDvE7zFoUpCa0',
    appId: '1:835117534469:android:012fe7fb93e447d30bbb6c',
    messagingSenderId: '835117534469',
    projectId: 'crud-tutorial-8cb44',
    storageBucket: 'crud-tutorial-8cb44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQp__FWO1qCYi4Bxq7UZJMmJ-5-b4e8E',
    appId: '1:835117534469:ios:c031f1bbe059b8980bbb6c',
    messagingSenderId: '835117534469',
    projectId: 'crud-tutorial-8cb44',
    storageBucket: 'crud-tutorial-8cb44.firebasestorage.app',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQp__FWO1qCYi4Bxq7UZJMmJ-5-b4e8E',
    appId: '1:835117534469:ios:c031f1bbe059b8980bbb6c',
    messagingSenderId: '835117534469',
    projectId: 'crud-tutorial-8cb44',
    storageBucket: 'crud-tutorial-8cb44.firebasestorage.app',
    iosBundleId: 'com.example.crudTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyfHaQsU2wVPKRDvvOcadfE2rglY3jpwI',
    appId: '1:835117534469:web:3e85ddf4145bc82d0bbb6c',
    messagingSenderId: '835117534469',
    projectId: 'crud-tutorial-8cb44',
    authDomain: 'crud-tutorial-8cb44.firebaseapp.com',
    storageBucket: 'crud-tutorial-8cb44.firebasestorage.app',
  );
}
